### ISSUE TITLE
Freezes when using the system tray service with KeepassXC

### ISSUE THREAD

**Issue by Anomalocaridid** [linkfrg/ignis#140]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

No

### System Information

 ```
Ignis 0.4.dev0
Branch: 
Commit:  ()
Current desktop: niri

os-release:
ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20250104.8f3e1f8"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"
```

### Description

When Ignis is using the system tray service and KeepassXC is set to create a tray icon, then opening KeepassXC or unlocking a database makes both Ignis and KeepassXC freeze for a relatively long time, about a minute or two.

### How to reproduce

1. Go to KeepassXC settings
2. Enable General>User Interface>Show a system tray icon
3. Close KeepassXC
4. Configure Ignis to have a system tray widget based on its system tray service. Some kind of clock widget would also be helpful to identify when it is frozen.
5. Run `ignis init` and keep it running in the background
6. Open KeepassXC. The window will appear, but you will not be able to do anything in it for a minute or two. The Ignis bar will also be frozen and not change or update.
7. After KeepassXC is unfrozen, unlock a database and it will freeze again for a similar amount of time.

**Comment by linkfrg** [comment]
should be fixed after [a331af](https://github.com/linkfrg/ignis/commit/a331affcd67284b5df2d6245390b8582faa8f27a)

**Comment by Anomalocaridid** [comment]
Using the latest commit of Ignis, I can confirm that KeepassXC with a tray icon enabled no longer freezes when it opens, but it still freezes when unlocking a database.

Also, now using it slows to an unusable crawl where the freeze seems to happen again and again after interacting at all with the GUI. For reference, before this, it was still usable, just annoying to wait for it to unfreeze.

Something that I neglected to mention that might be relevant is that KeepassXC changes its tray icon depending on it is locked or unlocked.

**Comment by linkfrg** [comment]
Looks like KeepassXC communicating through D-Bus **too** slow, Ignis freezes because it waits replies from KeepassXC.
This can be checked by setting the maximum timeout to 1 or 2 seconds in ``DBusProxy.__get_dbus_property``, the item will have no menu, title etc.
Overall I have one idea (get d-bus properties asynchronously), but this will require rewriting some  internal stuff of `SystemTrayItem` class

**Comment by linkfrg** [comment]
I opened #147, could you test it?
For me, launching and unlocking database doesn't cause freezes after this.

**Comment by Anomalocaridid** [comment]
> I opened [#147](https://github.com/linkfrg/ignis/pull/147), could you test it? For me, launching and unlocking database doesn't cause freezes after this.

#147 works perfectly with KeepassXC!

The only minor issue I noticed was that for some reason, the system tray for [Vesktop](https://github.com/Vencord/Vesktop) initially lacks an icon and takes a while to get one. However in my opinion, it is so minor, it is practically nothing in comparison.

**Comment by linkfrg** [comment]
> Edit: Apparently, even with the version of Ignis I was already using, Vesktop takes a while to make a system tray, so I think that part of the problem is on Vesktop's end and Ignis just immediately shows the system tray entry without waiting for an icon because that is handled asynchronously now.

Some applications such as Vesktop exports their icons as an `IconPixmap` - a list of integers representing the icon.
In the case of Vesktop, this data is huge.

Gio returns results from D-Bus method calls as a ``GLib.Variant``, and to operate with it you have to unpack it, which means converting this variant to a native python object.
And this seems to be the root of the problem: it takes a long time to unpack a variant with the icon of Vesktop, probably due to slowness of Python and it's built-in types.

To prevent the mainloop from blocking (prevent Ignis from freezes), I used `Utils.ThreadTask()` to unpack the variant in another thread: cba319f.

But this is not a real fix, I have a couple of ideas for a solution:

1. Speed up the unpacking process (using C, it will be hard because I don't know it)
    1. Write a C extension that converts `GLib.Variant` to a native python object. Honestly, I’m not at all sure if it will help.
    2. Write a C extension that creates `GdkPixbuf.Pixbuf` directly from `GLib.Variant` using only C stuff. this should already help

2. Try to create `GdkPixbuf.Pixbuf` directly from `GLib.Variant` using only Python. Pixbuf can be created from `GLib.Bytes` and and if it's possible to extract it from `GLib.Variant` then there are no special problems (I hope)
